### PR TITLE
 Add support to delete references between entities by absolute URIs

### LINKED ISSUE #194: Unlink
Hey people, 

So my 2 days of pain can benefit everyone I hope.  Here are the details of my findings:

The problem we had was a routing issue.  All the tests here against Unlink seem to send a URI to WCF service not a Web API.
This has come about by reading the specifications of OData, which clearly state that a relative path may be used in the query options for deletions.  
A URI resembling the following would be sent: http://host/entity(id)/navProperty/$ref?$id=navProperty(key)

This is correct, and is a valid _relative_ path for a wcf service.  Eg. http://host/service.svc

HOWEVER

This is not a valid _relative_ path for an ASP Web API. Eg. http://host/
Therefore, the WebAPI had no idea what to do with a URI using a relative path.
To get this working with a Web API you must pass a fully qualified URI in the query options like this: http://host/entity(id)/navProperty/$ref?$id=http://host/navProperty(key)

This very small difference allows the Web API to properly find a route, which must be defined in your controller as follows:

//Actual web request URL will look like: http://host/Teachers(key)/Students/$ref?$id=http://host/Students(studentId)
        [HttpDelete]
        [ODataRoute("Teachers({key})/Students({studentId})/$ref")]
        public IHttpActionResult RemoveStudentWithId([FromODataUri] Guid key, [FromODataUri] Guid studentId)
        {
            return Ok("Teachers(" + key + ")/Students(" + studentId + ")");
        }

When I say Web API I mean an ODataController based webservice class.  I can provide a sample test project if needed.

### LINKED ISSUE #441: How to unlink entities in many to many relationship?
As described in #194 when unlinking Simple.OData performs a DELETE call to http://host/entity(id)/navProperty/$ref?$id=navProperty(key).  However the OData v4 spec requires a full url (http://host/navProperty(key)) and and the OData WebApi framework will not route correctly unless a full url is provided.

Am I missing something?  Surely a fundamental operation like updating relationships hasn't been broken for 2+ years.  Is there another way to delete relationships or to make this work?

### PR DESCRIPTION
**Pull request by Discjoggy**
This PR closes #441, closes #194

Unlinking references in OData v2 and v3 endpoints is quite different to v4 and v4.01 endpoints. While versions before v4 using the `http://host/service/$links/NavigationProperty` template, versions of v4 or v4.01 must implement this `http://host/service/Entity(id)/NavigationProperty/$ref` template to address entity references. On top of that, there are two different ways to delete **collection** of references:

1. `DELETE http://host/service/Categories(1)/Products/$ref?$id=../../Products(0)`
1. `DELETE http://host/service/Products(0)/Category/$ref`

The spec of [Odata v4.0 - 4.4](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752345) contains the following text:

> Resource paths addressing collection of references can be used in DELETE requests if they are followed by the system query option $id identifying one of the entity references in the collection. **The entity-id specified by $id may be expressed absolute or relative to the request URL.**

The Simple OData Client only supports the last (relative uris) option. This PR adds a way to support the first (absolute uris) option too as an opt-in (no breaking change)by just setting a new simple `bool UseAbsoluteReferenceUris` property of the `ODataClientSettings` to `true`.

_Additional Information_

This PR is relevant because OData + ASP.NET Core apps actually doesn't support relative URIs and it can be used as a workaround until [this issue](https://github.com/OData/WebApi/issues/869) is fixed.

### CODE REVIEW

**Comment by object** [comment]
Thanks a lot! Merging it now.

**Comment by lordmampf** [comment]
Hello ;)

I have an issue with the absolute urls. For me the url missed a part.
Also when the `_session.Settings.BaseUri` did not end with an '/' the concatenation did not work.

Could you please check if this commit makes sense?

https://github.com/lordmampf/Simple.OData.Client/commit/388be152e2cbf9e35f47e3da87e6f238a2016acf

I'm very new to odata, so maybe I missed something ;)

**Comment by lordmampf** [comment]
I'm getting this url:

`
.../Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/apiMember(82118769-e4e6-4b0f-a807-ad0c937a6290)
`
instead of

`
.../Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)
`

**Comment by Discjoggy** [comment]
Hi @lordmampf 

> Also when the _session.Settings.BaseUri did not end with an '/' the concatenation did not work.

Thank you! I totally agree with you. Somehow this special case never hit when I was manually testing the different url cases.

> I have an issue with the absolute urls. For me the absolute url missed a part.
> I'm getting this url:
> 
> .../Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/apiMember(82118769-e4e6-4b0f-a807-ad0c937a6290)
instead of
> 
> .../Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)

I don't think that a part is missing. The first url should be the correct one, because the `$id` looks like the correct reference link to the `apiMember` with the identifier `82118769-e4e6-4b0f-a807-ad0c937a6290` (this is what you could use directly as a decoupled GET request). The second part just repeats the first part and doesn't really make sense. Please take a [look the official specs](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752345). Would you agree with that?

Your commit looks good, but I would suggest using the already existing `CreateAbsoluteUri` method which contains this part (makes sure that every URL ends with as `/`):

```cs
// ..
if (!basePath.EndsWith("/"))
                basePath += "/";
// ..
```

What do you think about this solution?

```cs
protected override string FormatLinkPath(string entryIdent, string navigationPropertyName, string linkIdent = null)
{
    var linkPath = $"{entryIdent}/{navigationPropertyName}/$ref";
    if (linkIdent != null)
    {
        var link = _session.Settings.UseAbsoluteReferenceUris
            ? Utils.CreateAbsoluteUri(_session.Settings.BaseUri.AbsoluteUri, linkIdent).AbsoluteUri + linkIdent
            : linkIdent;
        linkPath += $"?$id={link}";
    }

    return linkPath;
}
```

I didn't delete the PR on my side and can fix it very quickly and open a separate PR. Otherwise, tell me that you will create a PR.

**Comment by lordmampf** [comment]
Hello @Discjoggy 

> What do you think about this solution?

I used the following to fix it temporarily 

https://github.com/lordmampf/Simple.OData.Client/commit/388be152e2cbf9e35f47e3da87e6f238a2016acf

But feel free to do another pr, because it's better to use a Utils method ;)



> I don't think that a part is missing. The first url should be the correct one,

I can not really find a detailed explanation in the specs about this absolute thing. I agree that the information is now sent twice, but I think using an invalid absolute url is also not really nice.


I'm using Microsoft.AspNetCore.OData 7.2.1 as the backend and it does not accept this:

`http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/api/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)`

but

`http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member/$ref?$id=http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)`

is working fine.


When I test on the Northwind Testservice


 
working:
`https://services.odata.org/V4/Northwind/Northwind.svc/Suppliers(1)/Products/$ref?$id=https://services.odata.org/V4/Northwind/Northwind.svc/Suppliers(1)/Products(1)`

... Maybe we need another config for that....

**Comment by Discjoggy** [comment]
Good point, I will try to find a better example of the specs, but the urls of the issues #441 and #194 are also looking very similar and I just tried to fix it. I am confused because I am also working with `Microsoft.AspNetCore.OData 7.2.1`. Do you have a small example?

I guess your api fails because may the correct endpoint is missing? Did you verify that you can call `http://localhost:5000/api/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)` with a GET request and do you get a valid response? If you would call `GET http://localhost:5000/api/Group(7024ec70-c9bb-4681-8c5e-8631a7783e5d)/Member(82118769-e4e6-4b0f-a807-ad0c937a6290)` instead, you would ty to request the referenced entity before the reference was created.

**Comment by Discjoggy** [comment]
[Here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api#remove-a-reference-to-an-entity) you will find more examples.

**Comment by lordmampf** [comment]
Thank you very much for the question and the examples.
Now I understand, that my urls were wrong.

The endpoint did not exists, because for me "Member" was the name of the collection ;)

Thanks for your detailed help and for the pr!

**Pull request merged**
