### PR TITLE
Do not send Prefer header on GET/DELETE requests under V4 #600

### LINKED ISSUE #600: Preference return=representation and return=minimal
Prefer: return=representation header seems to get added to GET requests when it should not. According to [http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793631](Odata Spec)

Looks like #119 has resurfaced again. Problem lies in RequestWriterBase --> CreateGetRequestAsync. I'm guessing the call to AssignHeaders(request) shouldn't be there.

### PR DESCRIPTION
**Pull request by watfordgnf**
[Per the V4 spec, GET and DELETE requests may not include a `Prefer` header](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793631). The V3 spec is less strict and does not explicitly forbid sending them, so I left it alone (perhaps someone relies on this?).

This should resolve #600 and allow headers to be set on GET/DELETE requests in the future (in contrast to #750).

[This is also best viewed with whitespace ignored.](https://github.com/simple-odata-client/Simple.OData.Client/pull/751/files?diff=split&w=1)

### CODE REVIEW

**Comment by object** [comment]
@watfordgnf 
This one looks good, is there any work left on it? Otherwise I can merge it and release.

**Comment by watfordgnf** [comment]
@object no I do not believe so, the original requester did not seem to need anything else.

**Comment by jbarotin** [comment]
@object I think this PR will perfectly fix #600

**Comment by object** [comment]
@watfordgnf Unfortunately the PR broke quite a lot of unit tests in WebApiOData.V4.Samples.Test, and I can't understand why. Can you run the tests on your machine?

**Comment by watfordgnf** [comment]
@object I ran them locally, but I'll pull and rebase against the updates since I did this work and run the tests again.

**Comment by object** [comment]
@watfordgnf I just merged quite a big PR that will sort it preparation of FluentCommands. You will most likely need to rebase this PR.

**Comment by watfordgnf** [comment]
No problem, I'm a bit behind in work so it may be a few days.

**Comment by object** [comment]
The project source code is under significant changes (see discussion here https://github.com/simple-odata-client/Simple.OData.Client/discussions/840), so if the PR is still valid, please resumbit it after the modernization activity is complete.

**Pull request closed without merging**
