### PR TITLE
Added support for TypeConverters

### PR DESCRIPTION
**Pull request by kedrzu**
Currently serialization/deserialization lacks of some sort of layer of abstraction.
Also, there is no support for converting OData `Edm.Date` and `Edm.TimeOfDay` to `DateTime` and `TimeSpan` respectively (and the other way).

Having in mind possibility to seamlessly add support for any other type in client's code, I added support for using a .NET `TypeConverter`.

Using `Convert.ChangeType` has it's drawbacks, as one cannot extend it in any way. Under the hood it's simply calling `IConvertible` method.

### CODE REVIEW

**Comment by object** [comment]
Thank you for the PR. Can you think about an example of its practical use that can be complemented with a unit test? This is small but core change, so I would like to better understand what it's solving. The easiest would be if you can write a test that shows how to apply your change to perform better conversion.

**Comment by kedrzu** [comment]
Sure.
Problem is, that type conversion is done inside `SimpleOdata.Client.Core` which has no reference to `Microsoft.OData.Core` and all `Edm` types.
This makes quite troublesome to add proper unit tests. 

Main reason for this, is that I stumbled upon a problem: I want to use OData endpoint providing me `Edm.Date` and `Edm.TimeOfDay` properties and I can have only DTO's that use `DateTime` and `TimeSpan` (Entity Framework compatibility issue).

**Comment by object** [comment]
But the tests can reference anything. And if the proposed change solves something for you, you should be able to write a piece of client of code that uses the new improvement. Which can then be turned into a proper test.

**Comment by NetTecture** [comment]
@object It would allow my conversion issues to be fixed finally - and forever, including when coming up with more custom api level types. I actually like that And it would totally in my eyes justify a new release, btw., including updates to the referenced libraries.

**Comment by object** [comment]
@NetTecture Can you think about a test that would expose this functionality? We are developers and should be explain functional changes in a more formalized way. When adding new features I always try to complement them with tests, and I wouldn't like to make an exception here.

**Comment by kedrzu** [comment]
I will try to prepare some tests, once I find some time in between my duties.

However it is not that simple considering relation between different projects in the package. Especially between core project and V3/V4 adapters. Maybe I would have to add some additional abstraction layer to be defined in the core project and implemented separately in V3/V4 adapters.

**Comment by NetTecture** [comment]
@object  #546 is one case (among some more on the same line) that contains code that iirc could be abstracted into this.

**Comment by object** [comment]
@kedrzu if writing tests for a new feature exposes design issues there are even more reasons to write such tests. Test is an excellent opportunity to preview API changes before they are published and can't be retracted. This is why I always try to write them for new features and encourage contributors to do the same.

**Pull request closed without merging**
