### PR TITLE
Avoid invalid navigation

### PR DESCRIPTION
**Pull request by mbauerdev**
The fluent API allows to navigate from one entity to another even if there are defined query parameter options on the source entity. This leads to invalid API requests. Basically, it should not be possible to apply query parameter options when switching context / types using `.NavigateTo(...)`. There are different places where the logic would be appropriate to apply - I decided to implement it at the first possible location - before parsing/executing the query.

Example:
```cs
await client
    .For("Products")
    .Key(1)
    .Select( // <<< this is invalid when calling .NavigateTo(...) afterwards
    .NavigateTo("Category");
```

Resulting request:
```
https://host/Products(1)?$select=Field1,Field2/Category
    Problem here:       |---------------------|
```

### CODE REVIEW

**Comment by object** [comment]
> Sorry, I did a bunch of PR's and completely missed to run the tests again before pushing this one. I was able to identify the problem quickly, but I'm not sure how to resolve it since it may be a result of an inconsistency in the library. While implementing my change, I expected `FluentCommandDetails.FilterIsKey` and the correlated `BoundClient.FilterIsKey` to be true when the resulting command text would result in a key-based query like `/Products(1)`.
> 
> Now, the `FilterIsKey` property is true, when calling `BoundClient.Key(1)`, but false when you use `BoundClient.Filter(x => x.PrimaryKey == 1`. Both versions will result in the same query...
> 
> Now, which of the following alternatives would you prefer?
> 
> * Invest some time to have a consistent behavior with the `FilterIsKey` property
> * Allow navigation when filters are present since I do not know if it is a PK-search or not
> * Prohibit navigation when filters are present which may prohibit PK-search using `BoundClient.Filter(...)`
> * Eliminate this feature completely

Let me refresh my memory about FilterIsKey and I will come back to you.

**Comment by mbauerdev** [comment]
Of course - no pressure on this... I just had the issue that I accidentally tried to expand a query on which I already defined a projection ($select). This one failed on the server and I thought it would be nice to recognize this issue while constructing the query using `BoundClient` (fail early)...

If its too complicated, I'm absolutely fine to revert these changes :-)

**Comment by mbauerdev** [comment]
@object, did you find the time to think about the `FilterIsKey` property and its impact on the client?

**Comment by object** [comment]
The project source code is under significant changes (see discussion here https://github.com/simple-odata-client/Simple.OData.Client/discussions/840), so if the PR is still valid, please resumbit it after the modernization activity is complete.

**Pull request closed without merging**
