### PR TITLE
Removed ability to dispose inner HttpClient and obsoleted the RenewHttpConnection option

### PR DESCRIPTION
**Pull request by nsarris**

### CODE REVIEW

**Comment by nsarris** [comment]
First commit is to remove the ability to dispose the HttpClient and obsolsted the relative property.

Next one is tricky and needs some decisions. My suggestions:
- If no HttpClient is passed in the constructor (through options or otherwise) a default static instance should be used. OnCreateMessageHandler/OnApplyClientHandler need to also be obsoleted. 
- Setting the timeout in options should not affect the client but rather be applied on the request (see https://thomaslevesque.com/2018/02/25/better-timeout-handling-with-httpclient/)

To maintain backwards compatibility (along with an obsoltion note that this will be removed in a later version):
- Temporarily maintain a cache dictionary of HttpClients on the baseuri
- Have the OnCreateMessageHandler/OnApplyClientHandler run once on each HttpClient construction for the same BaseUri/API.

This will break the following senario:
- Having a different client configuration for the same API. I don't see a valid use case but this can be resolved through proper pairing of the HttpClient and ServiceAPI through HttpClientFactory (more on that below). If the need is to passthrough the windows user from an external call, then a single client with UseDefaultCredentials and a delegating handler works. 

And finally for the HttpClientFactory support. As it stands the IODataClient is very similar to the HttpClient in a sense that they both need to be paired together with a higher order service for dependency injection. I suggest a new DependencyInjection name space (perhaps on a separate project/nuget) that provides something like the following (built on top of HttpClientFactory and the AddHttpClient extension methods):

services.AddODataClient<IMyODataService, MyODataService>(
	serviceProvider => new ODataClientSettings {
		//settings 
	},
	serviceProvider => new HttpClient {
		//httpclient/handler buildup 
	})


 where MyODataService has a constructor that includes an IODataClient. 

If you need to different ODataClients on the same service, unfortunately the only thing to do is inherit the client and the interface.

@watfordgnf your thoughts please

**Comment by NetTecture** [comment]
Just a stupid question - why not go "all the way" and use the HttpClientFactory? This allows a user of this library to configure policies to be applied to all http requests based on destination i.e.

**Comment by object** [comment]
@NetTecture @watfordgnf Need your opinion on this one.

**Comment by watfordgnf** [comment]
I don't think we're at a point where this is ready to merge. @NetTecture brought up a good point regarding `HttpClientFactory`. I've not yet had the opportunity to see how this PR would look against our code base. We explicitly manage the `HttpClient` instances, but would enjoy moving away from that.

**Comment by NetTecture** [comment]
I actually am more or less stupid on that one. My knowledg o HttpClientFactory is "theoretical", but to my knowledge it takes the PRICE out of HttpClient, so it may be beneficial to have one with the same lifettime as odataclient or even go down to a per request level. Basically making it similar to a database connection with pooling below. Plus it is a central place to reconfigure settings and work with named settings. Good.

https://dev.to/xhantimda/introducing-the-httpclientfactory-3ege

The BAD side is that this is NetCore 2.1 as per that link, though https://stackoverflow.com/questions/51498896/use-httpclientfactory-from-net-4-6-2 indicates that Microsoft.Extensions.Http already has it and ca nbe sused in .NET Standard 2.0. I would prefer NOT fracturing the codebase per version and I would prefer not to have conditional code paths.

**Comment by nsarris** [comment]
I agree about avoiding version/framework fracturing that's why I didn't include Microsoft.Extensions.Http, but rather opted for a refactoring that would allow a DependencyInjection package on top of the client itself. 

I have a pretty good grasp of how the HttpClientFactory works underneath, and it pretty provides two options:

- Registers a named instance of an HttpClients and adds ability to bind services to that client
- Binds a service with an named httpClient instance (the service type name is used as the name underneath - this option provides one to one binding)

Under the hood it uses ActivatorUtilities from DependencyInjection that scans the constructors of the specified service to find one that includes an HttpClient and tries to construct it by resolving the rest of the parameters through the service provider and injecting the bound HttpClient.

However, I believe the granuality of the ODataClient is per configuration. This is why I built the low level self management around the base uri. On my own project built on top of Simple (targets Microsoft CDS) I have build a DI implementation that mixes HttpClientFactory and named configurations to achieve something like this:

```csharp
            services.AddCdsODataClient(
                "dynamics365",
                serviceProvider => GetConfiguration(),
                httpClient => httpClient
                    .AddHttpMessageHandler<RetryDelegatingHandler>(),
                builder => builder
                    .AddCdsODataTypedClient<AccountService>());
```

Essentially you bind a name (could be even ommited and autoproduced), a configuration, an httpClient along with its buildup of handlers etc and all services bound to this client.  

This works without any changes in Simple obviously by injecting the HttpClient in an ODataClientSettings. 

This was pretty much what I had in mind. I just commited the foundations to build propret DI support on top.

**Comment by object** [comment]
The project source code is under significant changes (see discussion here https://github.com/simple-odata-client/Simple.OData.Client/discussions/840), so if the PR is still valid, please resumbit it after the modernization activity is complete.

**Pull request closed without merging**
