### PR TITLE
Modernization

### PR DESCRIPTION
**Pull request by davidnmbond**
All modernization minus global namespaces

### CODE REVIEW

**Comment by robertmclaws** [comment]
This pull request changes spaces to tabs and makes every file have 100% changes. Any chance that can be changed back so that we can identify what the real changes are, please?

**Comment by mbauerdev** [comment]
@robertmclaws Agree on both points. C# indention is commonly done by 4 spaces and in most projects I know, there's a rule putting exactly one blank line between bodied class-members.

**Comment by davidnmbond** [comment]
> This pull request changes spaces to tabs and makes every file have 100% changes. Any chance that can be changed back so that we can identify what the real changes are, please?

You can turn off whitespace in the comparison.

> Also, as long as we're making formatting changes, can we add a line break between methods? Right now it's like reading a run-on sentence, there's no space for your brain to move between concepts.

Agreed re: line breaks between methods, properties etc., though this will have a similar issue with many files being touched.

I do realise that this is a pain, but I have applied these changes as a series of commits, each one citing the standard being adhered to post-change.  It may be easier to go through each commit to see my process.

**Comment by davidnmbond** [comment]
> Also, as long as we're making formatting changes, can we add a line break between methods? Right now it's like reading a run-on sentence, there's no space for your brain to move between concepts.

IDE2003 fixes applied - this should meet your readability needs!

**Comment by davidnmbond** [comment]
IDE2003 fixes should resolve the run-on sentence issue.

**Comment by davidnmbond** [comment]
OK everyone - any final objections before this is merged into master?

**Comment by rafek1241** [comment]
@davidnmbond 
Where can we find a changelog what happened there?
`IDE00XX` is not descriptive enough.

**Pull request merged**
