### PR TITLE
Allows controlling the life time of HttpClient externally

### LINKED ISSUE #416: Reduce instantiations of HttpClient
@object At the moment every Session has it's own HttpClient which means in the scenario of a web application talking to an API, I have as many HttpClient instances as concurrent users. This is contra-indicated by a number of MS/SO articles as it can lead to port exhaustion etc.; I also see multiple simultaneous request for GetMetadataAsync etc which are expensive.

Would you consider a pull request that adds an option to pool Session objects with this being controlled by an ODataClientSettings value. I think with this I could come up with a mechanism to only allocate one HttpClient per endpoint.

### PR DESCRIPTION
**Pull request by weitzhandler**
The problem with the current implementation is that it retains the same `HttpClient` for the entire lifetime of the `ODataClient`, its settings or session.

As explained [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core) and [here](https://github.com/dotnet/corefx/issues/11224), one of the main purposes of the IHttpClientFactory is to renew it because otherwise it doesn't respect DNS changes.
Additionally we want to be able to give the instantiation lifetime-management and disposal of the `HttpClient` completely over to external services, such as `IHttpClientFactory`.

The solution is adding an additional factory delegate that is requested whenever a `HttpClient` is required by the OData client infrastructure.

Fixes #416.
Related #502.

### CODE REVIEW

**Comment by object** [comment]
Thank you for the PR. I will go review the code, test it and come back to you.

**Comment by object** [comment]
I reviewed your PR, and since you touch some core principles, we need to discuss a few things or maybe rework.

1. Currently the lifetime of HttpClient is controlling by HttpConnection class, and ODataClientSettings have a flag RenewHttpConnection. If it's true, then on each request a new HttpClient instance is created, otherwise a new instance of HttpClient is created. In addition HttpConnetion uses other ODataClientSettings properties, such as BaseUri, Credentials, RequestTimeout, OnCreateMessageHandler, OnApplyClientHandler.

2. Introducing HttpClient factory eliminates all of the properties above - if HttpClient is controlled externally, none of them are in use. This can be confusing because suddenly the set of ODataClientSettings properties consist of incompatible items. I am strong believer in Yaron Minsky's principle "make invalid state non-representative", i.e. design state in such a way that it's not possible to combine incompatible values. So instead of just adding yet another property we may need to split ODataClientSettings into smaller classes (which will make a major version upgrade).

3. Why virtual HttpClient property? ODataClientSettings is not meant to be overridden (it can probably made sealed). This library has "simple" word in its name, I can't think of a sufficient reason to provider such virtual property. Won't OnGetHttpClient be enough?

**Comment by weitzhandler** [comment]
Hey, thanks for your detailed reply Vagif!

>1. Currently the lifetime of HttpClient is controlling by HttpConnection class, and ODataClientSettings have a flag RenewHttpConnection. If it's true, then on each request a new HttpClient instance is created, otherwise a new instance of HttpClient is created.

I wasn't aware of that, I'll make a new commit taking that option into account.

>In addition HttpConnetion uses other ODataClientSettings properties, such as BaseUri, Credentials, RequestTimeout, OnCreateMessageHandler, OnApplyClientHandler.

If we have the `HttpClient` controlled externally, I think taking care of the handlers, base address, and all the stuff that are contained in the `HttpClient` can be disregarded, since they are configured with the HttpClientFactory.

> 2. So instead of just adding yet another property we may need to split ODataClientSettings into smaller classes (which will make a major version upgrade).

That makes perfect sense. How about having `ODataClientSettingsBase` that requires a `HttpClient` factory, and on top of that, the regular `ODataClientSettings` adding those options and throwing an exception when trying to set the factory stuff etc. + documentation?

> 3. Why virtual HttpClient property? ODataClientSettings is not meant to be overridden (it can probably made sealed). This library has "simple" word in its name, I can't think of a sufficient reason to provider such virtual property. Won't OnGetHttpClient be enough?

Anything that's not sealed is virtual. I personally inherited it so it's easier for me to set the request/response receptors in its constructors. It's easier to make your `AppODataClientSettings` rather than statically type it in when you're constructing it. I prefer it should be open and virtual rather than sealed, I mean why not?

**Comment by object** [comment]
"Anything that's not sealed is virtual." Then let's seal the class! :-)

I think such basic stuff like a set of settings deserve to be simple without possibilities for hierarchies. Code base should comply to certain style, otherwise it will become unmanageable. Either virtual properties or set of handlers and factories. This library has chosen latter approach. I still see no reason for having a HttpClient property once there is a factory property.

And I am more in favor of containment than inheritance. Perhaps not ODataClientSettingsBase but a property instead that points to either externally resolved HttpClient or a set of settings to create internal one. Needs some thoughts.

**Comment by weitzhandler** [comment]
> I still see no reason for having a HttpClient property once there is a factory property.

Makes sense.

**Comment by weitzhandler** [comment]
> And I am more in favor of containment than inheritance. Perhaps not ODataClientSettingsBase but a property instead that points to either externally resolved HttpClient or a set of settings to create internal one. Needs some thoughts.

Maybe an external `HttpClientSettings` type as property, but that's a major breaking change.

**Comment by object** [comment]
Yes, this will be a major breaking change. The semantics of ODataCientSettings will be changed so much that this class will need redesign to stay consistent. I will create a new branch v6 and put a draft of a new ODataClientSettings there, to give you an idea of how it might evolve.

**Comment by object** [comment]
I thought about your proposal more. Can't what you suggest be achieved by using IHttpClientFactory with typed client, as described here? 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#typed-clients

You can configure services like this:
services.AddHttpClient<ODataClientSettings>();

Then the class that will execute requests will have a constructor that takes ODataClientSettings and can be instantiated via dependency injection. Inside this class ODataClient can be created by invoking a constructor taking ODataClientSettings:

var client = new ODataClient(settings);

This should work without adding OnGetHttpClient.

**Comment by weitzhandler** [comment]
It could, but since the `ODataClient` has longer lifetime and additionally, it's not the `ODataClient` that uses the `HttpClient` but its internal components such as `HttpConnection`, we want to delegate its disposal as well.
I'm hope @ryanowak could share his knowledge here for best practice.

**Comment by weitzhandler** [comment]
It could, but since the `ODataClient` has longer lifetime and additionally, it's not the `ODataClient` that uses the `HttpClient` but its internal components such as `HttpConnection`, we want to delegate its disposal as well.
I'm hope @rynowak could share his knowledge here for best practice.

**Comment by object** [comment]
> It could, but since the `ODataClient` has longer lifetime and additionally, it's not the `ODataClient` that uses the `HttpClient` but its internal components such as `HttpConnection`, we want to delegate its disposal as well.
> I'm hope @rynowak could share his knowledge here for best practice.

Why should ODataClient have longer lifetime? Nothing prevents a client app to create a new instance of ODataClient for each OData request, and if used in combination with typed HttpClient, a proper new instance of HttpClient will be applied.

**Comment by weitzhandler** [comment]
For some reason I understood that `ODataClient` should be used as singleton because it caches some of its stuff, if I was wrong, this PR can be closed.

**Comment by object** [comment]
The most critical for performance are EdmMetadataCache and TypeCache, both of them are static, i.e. its instances live outside ODataClient. ODataClient doesn't need to have long lifetime.

**Comment by weitzhandler** [comment]
I should have checked that, sorry.
And thanks for your dedication.

Maybe it would still be a good idea to add an external ex. method on `IServiceCollection` called `AddODataClient` with a settings action.

**Comment by object** [comment]
Yes, that makes sense. Thanks for the tip.

**Comment by weitzhandler** [comment]
Should I PR?

**Comment by weitzhandler** [comment]
Or you're going to update the settings anyway?

**Comment by object** [comment]
> Should I PR?
> Or you're going to update the settings anyway?

No, I no longer plan to update settings now. PR is appreciated.

**Comment by rynowak** [comment]
> I thought about your proposal more. Can't what you suggest be achieved by using IHttpClientFactory with typed client, as described here?

FYI - this is usually what I end up recommending for libraries that do HTTP. 

The person using a resource is the one who knows how to manage its lifetime. Libraries can't effectively hide the problem of managing connections for you without baking in a lot of opinions.

**Pull request closed without merging**
