### PR TITLE
Missing ConfigureAwait calls, causing deadlocks, added.

### PR DESCRIPTION
**Pull request by kgenov**
Hi Vagif,

Here are the changes which fixed my deadlock issues. All works as expected now with CRM, obviously i was getting the deadlocks only with CRM because they are on V4, and the problem was in the V4 adapter.

Regards,
Kiril

### CODE REVIEW

**Comment by object** [comment]
Thanks a lot! I will merge it soon.

**Comment by phatcher** [comment]
There's a few more, you can find them if you look for "await .*cancellationToken\);" via regex in Visual Studio

**Comment by kgenov** [comment]
Done.

**Comment by object** [comment]
Merged and released version 5.6.3. Thanks for the PR, @kgenov!

**Pull request merged**
