### PR TITLE
Make ODataClientSettings readonly accessable

### PR DESCRIPTION
**Pull request by waznico**
To create an unit test to check if settings were correctly set/applied, I've created a public readonly property. I want to use it, when I write a wrapper to create an ODataClient object and configure it within that wrapper method.
Currently it's not possible to check if the return Result (ODataClient) is correctly configured.

### CODE REVIEW

**Comment by watfordgnf** [comment]
`ODataClientSettings` is a mutable object, exposing it after the creation of the `ODataClient` may give users the wrong impression that it is reasonable to mutate the object during usage. It also sounds like you're duplicating test responsibility from this project in your project.

What settings are you configuring that you need to test after creation of the client that this package does not already test?

**Comment by object** [comment]
@waznico In general I am against exposing internal just for testability, especially when it can confuse users (and in this case might as @watfordgnf pointed out). In tests settings are usually created upfront and then used for executing the test action. Why would anyone need to read these settings again?

**Comment by waznico** [comment]
Thank you for your feedback. I reviewed the code again and maybe it's not correctly set up. My method sets some headers in the odata config and applies the config to a new client object, which will be returned. For me the simplest solution to test it was to set up an unit test which checks if the config was correctly applied to the client.

**Comment by object** [comment]
Sorry for late response. I believe this doesn't justify exposing settings. It's client code that controls settings and instantiate with them ODataClient instance. So I still don't see the reason for client to be able to access it afterwards.

**Pull request closed without merging**
