### PR TITLE
Value conversion fixes

### PR DESCRIPTION
**Pull request by mbauerdev**
**Support internal converters for own primitive types (structs)**
Unfortunately, the current implementation does not allow to define / activate custom type converters. This is why I added some alternatives to `TypeCache.TryConvert` and also streamlined the changes with the obsolete `TypeCacheExtensions.cs` implementation.

**Ignore indexer properties during conversion process**
Indexer properties were threated as normal properties and therefore, failing during conversion in certain circumstances.

**Removed duplicate test class (ValueConversionTests.cs)**

### CODE REVIEW

**Review by mcattle — APPROVED** [review]

**Comment by mbauerdev** [comment]
@mcattle Thanks for approving the PR - can you merge it into the master branch? Its still in "Open" state...

**Comment by mcattle** [comment]
@mbauerdev Unfortunately I don't have write access to this repository in order to merge. Quite frankly I was surprised that I had approval powers, but I did review the code and it looks good.

Mind you, I've just opened a PR that adds additional test cases to ValueConversionTests.cs, so that may need resolving, depending on who gets merged first. 🙂

**Comment by mbauerdev** [comment]
@mcattle Thank you for reviewing my changes - glad to hear that they look fine... Hope that the PR gets merged soon since my company (repo here: https://github.com/SwissLife-OSS/) is waiting for this feature ;-)

**Comment by mcattle** [comment]
Correction, PR #828 adds tests to the test class that wasn't removed as a duplicate, so there won't be any merge conflicts.  Here's hoping both our PRs get merged soon.

**Comment by object** [comment]
Sorry for the delay. Reviewed, ran tests, merging.

**Pull request merged**
