### PR TITLE
Fix #806 Strong name the assemblies

### LINKED ISSUE #806: Reconsider strong naming the assembly for the NuGet packages
Hi, we are evaluating the use of this library in order to replace access to Sharepoint data currently done with CSOM, which is not supported on net fw > 4.8. In the Sharepoint world, it is customary to strong name assemblies in order to avoid issues with assembly versioning and GAC copies.

I have seen issue #155 where you describe the ideological reason for not applying a strong name. I understand those, but I would urge you to reconsider. The world is a different place from 2015 (even the links you reported are dead now!) and while I agree that signing code is an exercise in futility, maintaining a clear binding between a distribute NuGet package and its source project is quite important. The guidelines for NuGet packages now explicitly encourage applying a strong name (https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries) . Signing keys do not require a password, you can just upload the .snk file to Github and have it shared with the world, keeping 100% OSS reproducibility of the package.
Basically, strong naming has now lost all of its former attachment to digital signatures and is just a unique name for a binary.

Thanks for your time and have a nice day.

### PR DESCRIPTION
**Pull request by lscorcia**
As discussed in #806 , this PR adds a passwordless strong name key and uses it to sign the assemblies.

### CODE REVIEW

**Comment by robertmclaws** [comment]
Just an FYI, strong-name signing is much easier to implement in Directory.Build.props, and then using an MSBuild variable to specify the key name.

See an example DBP here: https://github.com/OData/RESTier/blob/breakdance-net5/src/Directory.Build.props
And how it's implemented in a signed project here: https://github.com/OData/RESTier/blob/breakdance-net5/src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj

Makes life SO much easier.

**Comment by lscorcia** [comment]
Nice to know! I wasn't aware you could set assembly properties with msbuild directives. If @object prefers this form I can force push a new version using the technique you mentioned.

**Comment by object** [comment]
I did not look into the details of the alternative approach but assuming it's simpler I prefer that.

**Comment by lscorcia** [comment]
It is simpler indeed. I force-pushed a new version of the pull request. Thanks @robertmclaws !

**Comment by robertmclaws** [comment]
No problem! Had to deal with that with Restier and it was a huge PITA.

One issue I will point out that happens with strong name signing, make sure that the AssemblyVersion stays stable even when you're publishing new build versions. I always end up having to do assembly binding redirects for OData and it drives me bonkers. The AssemblyFileVersion can be 3.4.12, but the AssemblyVersion in that situation should remain 3.4.0.0.

Just something to keep in mind, it's the first thing that bites strong-name signers in the butt.

**Comment by object** [comment]
Came back from vacation, now I can do the merge. Decided not to bump major version, can't see this change can break anything. This is released as the version 5.24.

Thanks for the initiative!

**Pull request merged**
