### PR TITLE
Support System.Text.Json 6.0 in v4 Client

### PR DESCRIPTION
**Pull request by robertmclaws**

### CODE REVIEW

**Comment by robertmclaws** [comment]
This is blocking several of our projects from moving to .NET 6.0.

**Comment by pocki** [comment]
Also our projects are blocked by this (useless) package dependency restriction.

Please remove the upper bound as it is only needed if there are any breaking changes in the next versions. There are none anounced.

**Comment by mbauerdev** [comment]
Nice one, thanks for that contribution <3

**Review by mbauerdev — APPROVED** [review]

**Review by davidnmbond — APPROVED** [review]
Looks good to me.

**Review by StefanWetterActiware — APPROVED** [review]

**Comment by davidnmbond** [comment]
OK - no movement - time to fork?

**Comment by ysmoradi** [comment]
@davidnmbond I think now is the time. I can handle this and in our organization, we're using this library heavily so there won't be an issue.

**Comment by davidnmbond** [comment]
> @davidnmbond I think now is the time. I can handle this and in our organization, we're using this library heavily so there won't be an issue.

Happy to help.  Give me a week to bring it up to our .NET 6.0 standards and I'll give you a shout.

**Comment by davidnmbond** [comment]
While we wait, and for those that desperately need it, check out the PanoramicData fork which updates all nuget packages and has drastically overhauled the code base against the latest C#10 standards:

https://www.nuget.org/packages?q=PanoramicData.OData
https://github.com/panoramicdata/PanoramicData.OData.Client

**Comment by mbauerdev** [comment]
Hey guys, please check out this issue I created some days ago: #835 
I think its a bad idea to fork the repository and end up with 20 competing versions. As I understood @object, he would like to find a way to improve the maintenance of this repository... Can't you wait until what @object decides?

**Comment by mbauerdev** [comment]
Btw, I do not like the idea to have any random company name in an open source product name. If the only viable option is to fork this repository, please consider a neutral name...

**Comment by object** [comment]
@ysmoradi (and others) sorry for late response and lack of maintenance activity from me in the last months. As I wrote in a different place, I haven't been using OData myself for more than 5 years, and at that time it was not even .NET Standard ready. All these years I've been doing develop,ment using different tool sets and even a different language (F#). And last couple of years having almost no time to add new features myself to this library, so I have to thank all of you for great contibutiion efforts.

I have been trying to find a proper replacement for myself, preferrably not a single person, just to avoid same situation again. Also having several people it's easy to avoid some design mistakes caused by individual decisions (which I did myself a few times). Your wish to continue developing the library looks promising, but I agree with @mbauerdev that just forking it might be an unnecessary step. Libraries are usually forked due to people being stuck with the original maintainer or due to differences in how to further develop them. While I can be classified as a burnout mainainer, I am willing to do my best to let the library develop live on supported by people who (unlike me) actively use OData and have inspiration to keep up with its new features.

So please think about what can be done to transfer library ownership (and its NuGet packages) from me to others.

**Comment by Robelind** [comment]
> While we wait, and for those that desperately need it, check out the PanoramicData fork which updates all nuget packages and has drastically overhauled the code base against the latest C#10 standards:
> 
> https://www.nuget.org/packages?q=PanoramicData.OData https://github.com/panoramicdata/PanoramicData.OData.Client

Seems to have the same problem.

**Comment by davidnmbond** [comment]
@object - Happy to merge all the C# updates back in.  The new PanoramicData package is functionally identical, but with a LOT of code maintenance issues resolved.  To merge it back in, you will simply need to globally replace "PanoramicData.OData" with "Simple.OData", including the folder names, csproj file names etc.

In the meanwhile, the PanoramicData.OData nuget packages are working and free for all to use.

**Comment by davidnmbond** [comment]
> > While we wait, and for those that desperately need it, check out the PanoramicData fork which updates all nuget packages and has drastically overhauled the code base against the latest C#10 standards:
> > https://www.nuget.org/packages?q=PanoramicData.OData https://github.com/panoramicdata/PanoramicData.OData.Client
> 
> Seems to have the same problem.

Yes - my mistake!  I've updated the package.  I hadn't actually factored in this pull request (facepalm).

**Comment by robertmclaws** [comment]
Also, something to consider, making your package reference look like this also solves the problem: 
```
    <PackageReference Include="Simple.OData.V4.Client" Version="5.*" NoWarn="NU1608" />
    <PackageReference Include="System.Text.Json" Version="6.*" NoWarn="NU1608" />
```

**Comment by pzbyszynski** [comment]
@object This PR seems like a quick fix. It would be great if you could merge it, because we are blocked with net6 migration, and ownership transfer does not seem like something that will happen any time soon

**Comment by pzbyszynski** [comment]
@robertmclaws Would you please consider fixing the same issue for `Simple.OData.Client`? I can create separate PR but it probably will be much quicker to merge this one

**Pull request merged**
