### PR TITLE
Upgraded symbol publishing

### LINKED ISSUE #653: Please add Symbols to the NuGet package
Hi,

I've encountered an issue using this library, and tried debugging it, but looks like the package is published to NuGet without the symbols.
Checking build.cmd it does look like the `-Symbol` is there, but apparently it doesn't come with the pdb files and is not debuggable.

### PR DESCRIPTION
**Pull request by weitzhandler**
Fixes #653.

### CODE REVIEW

**Comment by watfordgnf** [comment]
So this creates the `.snupkg` file and also includes the pdb's in the main `.nupkg`?

**Comment by weitzhandler** [comment]
Hopefully. Haven't tested it in production, but according to [this](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/) article, that's the way to go.

**Comment by weitzhandler** [comment]
Yes, according to [this](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/).

**Comment by object** [comment]
Released 5.9.2.

**Comment by weitzhandler** [comment]
Unfortunately that doesn't seem to have worked 😢

Maybe we need to include all the source files? That's weird no?

image

**Comment by object** [comment]
@weitzhandler no, including sources are ridiculous. I can't see anything wrong in your PR. Will have a closer look today, perhaps it's time to shoot a question on SO.

**Comment by object** [comment]
I believe the problem was that the script was publishing to http://nuget.org. I changed it to https://api.nuget.org/v3/index.json, and now I can see symbols. Publishing 5.10.0.1 now.

**Comment by weitzhandler** [comment]
You are awesome, thank you!

**Pull request merged**
