### PR TITLE
allow custom adapter factories to support extending the default adapters

### PR DESCRIPTION
**Pull request by paulkroener**
Added IAdapterFactory to ODataClientSettings to make it possible to easily extend default adapters. My use case is to extend the BatchWriter to add custom query string parameters, headers and logging of subrequests.

related: https://github.com/simple-odata-client/Simple.OData.Client/issues/413

### CODE REVIEW

**Comment by object** [comment]
Hi Paul, and thank you for the PR. It's looking good, however we always try to write tests for changes.  Can you think of some unit tests that would demonstrate the usage of custom adapters (and will of course protect the code from regression bugs)?

**Comment by paulkroener** [comment]
Good point, I added a test. Could not think of anything else than this rather simple one ;-)

**Comment by paulkroener** [comment]
Added a more comprehensive test. What do you think?

**Comment by object** [comment]
> Added a more comprehensive test. What do you think?

I think it looks very good because it illustrates the reason for creating custom adapters, so it will help people understand why and when they should go for customization. I will run some tests and hope to merge it by the end of the day. It will be released as version 5.8.

**Pull request merged**
